[tool.poetry]
name = "my-app-name"
version = "0.1.0"
description = "A sample app"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
flask = "^2.3.0"
firebase-admin = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
